### ISSUE TITLE
go 1.7 support

### ISSUE THREAD

**Issue by allspace** [jacobsa/fuse#17]
"golang.org/x/net/context"

this has been builtin package in 1.7.

**Comment by jacobsa** [comment]
It's true, but the two packages are functionally equivalent and the code continues to build under Go 1.7. Have you seen an actual problem?

**Comment by allspace** [comment]
yes, look at the package name "golang.org/x/net/context"

with 1.7 builtin, it should be just "context"

my workaround is to create a directory structure golang.org/x/net, and link context with builtin one.

**Comment by jacobsa** [comment]
Again, the old package continues to exist. As far as I know, it is still compatible with Go 1.7. I certainly haven't seen any trouble on Linux or OS X. Okay yes it requires you to download the package, but `go get -u` makes that easy.

Anyway, please feel free to send a pull request.

**Comment by kahing** [comment]
this is fixed by https://github.com/jacobsa/fuse/pull/39 ?
