### ISSUE TITLE
fuse: support for oxfuse 3.5.2

### ISSUE THREAD

**Issue by rjeczalik** [jacobsa/fuse#19]
Hey @jacobsa!

Mounting with the `fuse` package fails with:

```
callMount: fork/exec /Library/Filesystems/osxfusefs.fs/Support/mount_osxfusefs: no such file or directory
```

Looks like the osxfuse in 3.5.2 version changed its structure, now [the binary](https://github.com/jacobsa/fuse/blob/master/mount_darwin.go#L20) is under `/Library/Filesystems/osxfuse.fs/Contents/Resources/mount_osxfuse`, however I'm not sure it's enough to fix the path.

Thus this issue.

**Comment by jacobsa** [comment]
Pull request #18 covers this. I will try to clean it up and get it committed during the 13 hour flight I'm about to board, but no promises.
