### ISSUE TITLE
Improving performance on gcsfuse mounted partitions 

### ISSUE THREAD

**Issue by skechboy** [jacobsa/fuse#26]
Hi,

I'm trying to enable FTP/SFTP access to Google Cloud bucket, by using Pure-FTP server on Google instance. However I'm experiencing some weird issue when I'm trying to delete file trough FTP, you can see this issue in more details [here](https://github.com/jedisct1/pure-ftpd/issues/56).

I'm suspecting that the ftp server is failing to address the DELETE request properly due to some small delays in gcsfuse mounted partitions. 

So my question is if it's there any way that I can solve this by tuning up gcsfuse performance. My current mount settings are: 

`backup /home/backup gcsfuse rw,auto,allow_other,uid=1001,gid=1001,file_mode=0777,dir_mode=0777`

Thanks

**Comment by jacobsa** [comment]
This sounds like it belongs on GoogleCloudPlatform/gcsfuse, not here. Closing this; please open there if you've still got concerns after the responses on the linked issue.

(If you do reopen there, I will need more details about what you think is happening. It may be worth knowing that renaming files is supported in gcsfuse and should be atomic, and renaming directories is not supported.)
