### ISSUE TITLE
is there anyway to increase ReadFileOp.Dst buffer size?

### ISSUE THREAD

**Issue by ruiyang2015** [jacobsa/fuse#28]
It seems in the OSX, the ReadFileOp.Dst callback always set Dst with 8K size, is there anyway to bump this size to a bigger number?

**Comment by jacobsa** [comment]
The size of the `Dst` buffer is controlled by the `Read` op sent by the kernel itself (cf. [conversions.go](https://github.com/jacobsa/fuse/blob/da343d6bf5157fc3186660d47909481fccb9b7da/conversions.go#L281-L291)). I don't know if osxfuse supports tuning this. It's possible it's controlled by the `iosize` mount options documented [here](https://github.com/osxfuse/osxfuse/wiki/Mount-options). Please report back if you try it.
