### ISSUE TITLE
could not install using go get

### ISSUE THREAD

**Issue by vk18vk** [jacobsa/fuse#42]
github.com\jacobsa\fuse\internal\fusekernel\fuse_kernel.go:171: undefined: syscall.O_ACCMODE
jacobsa\fuse\internal\fusekernel\fuse_kernel.go:397: undefined: Attr

**Comment by jacobsa** [comment]
Is this windows? It's not expected to work on windows.

**Comment by vk18vk** [comment]
ohhh yes its windows, anyway thanks for the information.
