### ISSUE TITLE
fails to build, "missing function body"

### ISSUE THREAD

**Issue by rowmoney** [jacobsa/fuse#43]
I'm trying to build a different project (kahing/goofys), which uses this project.  I'm using a Rock64 running Ubuntu 17.10 armhf, actually aarch64 architecture.  I get this error message:

**Comment by rowmoney** [comment]
Sorry, I'm on my phone

rock64@rock64:~$ go get github.com/kahing/goofys                                                            
# github.com/jacobsa/fuse/internal/buffer                                                                   
work/src/github.com/jacobsa/fuse/internal/buffer/runtime.go:24: missing function body for "memclr"          
work/src/github.com/jacobsa/fuse/internal/buffer/runtime.go:29: missing function body for "memmove"

I saw the same thing in a closed issue from a year ago, and the guy said he figured it out - but I'm less knowedgeable than he was and don't understand his solution.  Any chance that change could be made now?

**Comment by stapelberg** [comment]
This was most likely fixed by https://github.com/jacobsa/fuse/commit/0630024b2bfb0724598a8dbccc5aa568b4379311
