### ISSUE TITLE
Support for ppc64le

### ISSUE THREAD

**Issue by YiannisGkoufas** [jacobsa/fuse#44]
I was trying to use this library https://github.com/kahing/goofys and getting an error from fuse:

```
panic: Page size is unexpectedly 65536

goroutine 1 [running]:
github.com/jacobsa/fuse/internal/buffer.init.0()
	/root/gopath/src/github.com/jacobsa/fuse/internal/buffer/in_message.go:33 +0xe4
```

So I assume it has to do with fuse.
Any hint on what it should change in order to get it working for ppc64le architecture?

**Comment by YiannisGkoufas** [comment]
Any hints on that one? :(

**Comment by hongjun0619** [comment]
@YiannisGkoufas

I have modified the files according to  your changing,but it still doesn't work:

panic: Page size is unexpectedly 65536


goroutine 1 [running]:
github.com/jacobsa/fuse/internal/buffer.init.0()
    /root/go/pkg/mod/github.com/kahing/fusego@v0.0.0-20200327063725-ca77844c7bcc/internal/buffer/in_message.go:33 +0xb8

**Comment by gaul** [comment]
#102 addressed this.
