### ISSUE TITLE
fuse.EISDIR not defined

### ISSUE THREAD

**Issue by DamonBlais** [jacobsa/fuse#51]
As per the documentation on `open(2)`, they can return `EISDIR` as a more specific error code when attempting to use this method on a directory.

I could not find an error code matching `syscall.EISDIR` defined in this package.

You defined `ENOTDIR` but not this code...

It should be defined.

**Comment by jacobsa** [comment]
Please don't open one issue per missing constant -- that's a little bit excessive.
