### ISSUE TITLE
fuse.EBADF not defined

### ISSUE THREAD

**Issue by DamonBlais** [jacobsa/fuse#55]
As per the documentation on `close(2)` and `close(3)`, when a file handle either does not exist or has gone stale, or has already been closed; this error should be returned.  Currently, one must return `EIO` or `EINVAL` as you have not given us the proper options.

I could not find an error code matching `syscall.EBADF` defined in this package.

It should be defined.

**Comment by jacobsa** [comment]
Please don't open one issue per missing constant -- that's a little bit excessive.
