### ISSUE TITLE
possible bug?

### ISSUE THREAD

**Issue by complyue** [jacobsa/fuse#65]
By using `:=` in the following places, I suppose the `err` variable declared in the return list is shadowed:

https://github.com/jacobsa/fuse/blob/cd3959611bcb6bb23d49f1598d98f2bf44476805/mount.go#L41

https://github.com/jacobsa/fuse/blob/cd3959611bcb6bb23d49f1598d98f2bf44476805/mount.go#L63

https://github.com/jacobsa/fuse/blob/cd3959611bcb6bb23d49f1598d98f2bf44476805/mount.go#L76

Isn't this a bug or I missed something?

**Comment by mhandugan** [comment]
This is a “feature” of Go. There is no shadowing in this scenario. 

https://golang.org/ref/spec#Short_variable_declarations

> Unlike regular variable declarations, a short variable declaration may redeclare variables provided they were originally declared earlier in the same block (or the parameter lists if the block is the function body) with the same type, and at least one of the non-blank variables is new. As a consequence, redeclaration can only appear in a multi-variable short declaration. Redeclaration does not introduce a new variable; it just assigns a new value to the original.

**Comment by complyue** [comment]
I see, I don't know why I (wrongly) assumed function result vars live in a separate scope.
thanks @mhandugan
