### ISSUE TITLE
fuse mount with root failed 

### ISSUE THREAD

**Issue by kungf** [jacobsa/fuse#76]
"mount: invalid argument"
this is the strace log
[strace.log](https://github.com/jacobsa/fuse/files/4305334/strace.log)

@stapelberg thanks

**Comment by stapelberg** [comment]
Does this only happen when you’re running as root, or also as your user?

If it happens only as root, can you try `sudo chown root.root /home/wangyang5/polefs/mnt` and see if that helps?

If this is blocking you, a workaround would be to add a check for syscall.EINVAL and return errFallback in https://github.com/jacobsa/fuse/blob/2f65426467b1505bddb90f7cb10f071607593679/mount_linux.go#L160

**Comment by kungf** [comment]
only root user has this problem

**Comment by kungf** [comment]
i find in `man 2 mount`

> EINVAL source  had  an  invalid superblock.
source is selfdefinde fsname "polefs-wy3", i am not sure how mount get the superblock of source?

**Comment by stapelberg** [comment]
> i find in `man 2 mount`
> 
> > EINVAL source  had  an  invalid superblock.

I don’t think this applies. The `mount` manpage was written for traditional file systems, not FUSE.

I just tried to reproduce the issue, but can’t:

From your log:

> 432551 mount("polefs-wy3", "/home/wangyang5/polefs/mnt", "fuse", MS_NODEV, "fd=12,rootmode=40000,user_id=0,group_id=0,default_permissions,subtype=polefs,allow_other") = -1 EINVAL (Invalid argument)

…but on my machine, this works fine:

> mount("distri", "/ro", "fuse", MS_NODEV, "fd=3,rootmode=40000,user_id=0,group_id=0,allow_other,default_permissions,subtype=polefs") = 0

Which Linux version are you running this on? What are the steps to reproduce this issue in a clean installation?

**Comment by kungf** [comment]
>Which Linux version are you running this on? What are the steps to reproduce this issue in a clean installation?
centos7 3.18.22 ,  do nothing special in after installation.

**Comment by stapelberg** [comment]
So I set up a CentOS 7 VM (from CentOS-7-x86_64-Minimal-1908.iso) and ran `yum -y update`.

However, I get kernel version 3.10.0-1062.12.1.el7.x86_64, not 3.18.22?

Furthermore, mounting the sample file system (samples/mount_sample) works fine:

```
[root@localhost ~]# strace -fvy -s2048 -e mount /tmp/mount_sample --ready_file 1 -type flushfs --flushfs.flushes_file=2 -flushfs.fsyncs_file=2 -mount_point /mnt
[…]
[pid  9781] mount("", "/mnt", "fuse", MS_NOSUID|MS_NODEV, "fd=3,rootmode=40000,user_id=0,group_id=0,default_permissions") = 0
[…]
```

Can you please actually reproduce your problem in a clean VM and share the precise steps to reproduce?

**Comment by stapelberg** [comment]
Okay, so the issue only manifests itself once you start setting the `Subtype` FUSE mount option.
