### ISSUE TITLE
Not compatible to fuse3

### ISSUE THREAD

**Issue by b6bcvsaan2** [jacobsa/fuse#84]
This version has been used on a CentOS 8 with only fuse3 installed without any problems except that only fuse 2.x commands are executed. The implementation should be aware to a Fuse 3 installation.

**Comment by stapelberg** [comment]
Let me know if https://github.com/jacobsa/fuse/commit/b6e2754edfa8ac864bd26efe8541ebf2ee6563eb fixes the issue for you. It works on my machine with fusermount3, but I don’t have a CentOS VM handy for testing.
