### ISSUE TITLE
why the pagesize is always 4096?

### ISSUE THREAD

**Issue by yangzhm** [jacobsa/fuse#89]
In fuse\internal\buffer\in_message.go the pagesize is setted by 4096.
Why? The system pagesize is 4K/16K/64K.

**Comment by stapelberg** [comment]
Depends on the architecture. https://en.wikipedia.org/wiki/Page_(computer_memory)#Multiple_page_sizes explains that on x86-64, it’s 4K or 2MB, and presumably you need hugepages enabled for 2MB.

I don’t think there was a conscious choice to not support other page sizes, it’s just that 4K works well everywhere and hence makes for a good starting point.

**Comment by yangzhm** [comment]
> Depends on the architecture. https://en.wikipedia.org/wiki/Page_(computer_memory)#Multiple_page_sizes explains that on x86-64, it’s 4K or 2MB, and presumably you need hugepages enabled for 2MB.
> 
> I don’t think there was a conscious choice to not support other page sizes, it’s just that 4K works well everywhere and hence makes for a good starting point.

Thanks for your explanation. 
I can change the size in source for adaptting to my system , but I do not know the effect.

**Comment by gaul** [comment]
#102 addressed this.
